### ISSUE TITLE
add_users_to_workflow email notifications incorrect

### ISSUE THREAD

**Issue by bart-quintens** [erwinmintiens/signinghubapi#14]
The add_users_to_workflow method uses **email_notifications** instead of **email_notification** which results in users added without notification.

**Comment by erwinmintiens** [comment]
Hi Bart, thanks for notifying me. I see your issue and I'm working on a patch for this. I'll get back to you as soon as possible

**Comment by erwinmintiens** [comment]
Hi Bart, please update the package to the latest version (v0.1.5):
`pip install signinghubapi==0.1.5`
The issue should be fixed there.
